application: blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest

# run dev_appserver.py app.yaml to start server
